### PR TITLE
Fast normalization algorithm for Brunerie number 😎

### PR DESCRIPTION
**Pull request by cangiuli**
A straightforward extension of the cubical group's current hacking projects at Dagstuhl...

### CODE REVIEW

**Comment by favonia** [comment]
A slower but absolutely sound algorithm is to compare (alpha equivalence only) whether it is one of the recognized implantations.

**Comment by favonia** [comment]
I did a simple profiling of this optimization and it finished even before I ran it! It's so fast that it created some time-space paradox.

**Comment by martinescardo** [comment]
The correct terminology should be "Brunerie's constant" and you need a Greek letter for it, such as β.

**Comment by mortberg** [comment]
Thank you Carlo! (closing :))

**Pull request closed without merging**
