### PR TITLE
Proper error handling when importing files

### LINKED ISSUE #64: Spurious error with incorrect import
We've noticed that if you import a nonexistent module (`import not-real`), you will receive a strange error that some identifier cannot be resolved, but this identifier doesn't have anything to do with the module that we failed to import.

We are guessing that the failed import is somehow messing up *another* import, which causes the identifier resolution error. (It seems to mess up just that imports that come before.)

I think it would be nice if when you import a nonexistent module, you got an error that said something like `module 'not-real' cannot be found`.

### PR DESCRIPTION
**Pull request by mortberg**
This fixes https://github.com/mortberg/cubicaltt/issues/64

### CODE REVIEW

**Comment by jonsterling** [comment]
Thanks @mortberg! I'll try to test this and the other PR tonight.

**Comment by mortberg** [comment]
@jonsterling : Did you try it out?

**Comment by jonsterling** [comment]
@mortberg Ahh, I lost track of it. I'll try it out right now.

**Comment by jonsterling** [comment]
Just tried it out and it seems to work! Sorry for the delay.

**Comment by mortberg** [comment]
Thanks a lot for testing it!

**Pull request merged**
