### PR TITLE
implement propositional truncation

### PR DESCRIPTION
**Pull request by abooij**
these basic facts about propositional truncations don't seem to be anywhere else yet

### CODE REVIEW

**Comment by coquand** [comment]
Unfortunately the implementation of recursive HIT (such as truncation
but not suspension) has not been fixed yet.
 Thierry

**Comment by martinescardo** [comment]
Fixed in theory or in the implementation? What about the circle, in particular? What goes wrong with the current implementation?

**Comment by coquand** [comment]
Fixed in the implementation.
 The problem occurs only for HIT with parameters. So the circle should be correctly
implemented.
 Hopefully the theory is all right. The paper on cubical type theory describes the semantics/type
theoretic rules for propositional truncation, which is surprisingly subtle.
The circle is also described
there and for the circle everything behaves in the theory as one expects. It is essential for this
to have a diagonal operation on names (and this was the motivation for introducing this operation).

**Comment by martinescardo** [comment]
Thanks, and good. What is wrong with the implementation of propositional truncation?
Where and how will I see a symptom of its incorrect implementation?

**Comment by simhu** [comment]
Thanks, Auke, for the patch!  Maybe we could add it with a disclaimer.  I propose to rename pTrunc into inh though.

Martin, if I recall correctly, there was an example of this wrong behaviour in:
https://github.com/mortberg/cubicaltt/issues/35
The problem is when defining the "squeeze" and "transp" functions (which are needed to define compositions for propositional truncation); the problematic case is for elements of the form VPCon (path constructors).

**Comment by abooij** [comment]
@simhu, I implemented your proposals.

**Comment by simhu** [comment]
Thanks and sorry that it took so long to merge...

**Pull request merged**
