### PR TITLE
Converted the project into a cabal project

### PR DESCRIPTION
**Pull request by abooij**
Using the new project structure, one can easily build, package, and install cubicaltt, even in a cabal sandbox (or using `stack` I guess, although I haven't tried):

```
$ cabal install alex happy bnfc
$ cabal install
```

### CODE REVIEW

**Comment by mortberg** [comment]
Will Setup.hs rerun bnfc if Exp.cf changes? I made a hack to do this for cubical:

https://github.com/simhu/cubical/blob/master/Setup.hs

It would be nice if it can be done without any hacks...

**Comment by mortberg** [comment]
Maybe bnfc should be added to the list of build-tools in the cabal file?

**Comment by abooij** [comment]
It runs `bnfc` every time you run `cabal build` (or whatever your haskell package build tool of choice is). `bnfc`, in turn, seems to only overwrite files that actually changed. However, I'm not sure cabal will automatically detect all resulting changes in the `Exp.*` modules, except for those listed in `other-modules`. So I'll list everything we need in `other-modules` to fix that in just a second.

`bnfc` is listed in `build-tools`...

**Comment by mortberg** [comment]
Oops, I was looking at the old cubical.cabal file where we had forgotten to put bnfc in the build-tools list and got confused. My bad!

**Comment by abooij** [comment]
If we can purge the `Makefile`, we can clean up a few things, like automatically updating the version in `Main.hs` using `Paths_cubicaltt.hs` (which is generated by cabal).

**Comment by mortberg** [comment]
I don't want to get rid of the Makefile for now. I think the system is far too experimental to be close to a release anytime soon, so automatically updating version numbers is not high on the priority list. However having a cabal build system is nice so I'll merge this now.

**Comment by abooij** [comment]
Yes, I agree, and that's why I did not include those changes just yet.

**Pull request merged**
