### PR TITLE
Add a few proofs to what currently goes for the "standard library"

### PR DESCRIPTION
**Pull request by abooij**
I wrote a bunch of utility functions that might be useful for other cubicaltt code. It is used in my 'chain' branch (which proves a chain of equivalences, nothing relevant but a nice exercise).

Cherry-pick what you like.

### CODE REVIEW

**Comment by abooij** [comment]
Notably this implements ordering of natural numbers.

**Comment by abooij** [comment]
In fact there are a handful of things that I would personally wouldn't like to see pulled. So perhaps you can make a list of what you like / don't like, and I can reorganize this PR.

**Comment by mortberg** [comment]
Looks good overall, but I think the best is just if you remove what you don't like and then I'll have a closer look at it.

**Comment by abooij** [comment]
Ok, on second review (with some minor changes which I already force-pushed) I think it's alright. Pull if you agree.

**Comment by mortberg** [comment]
This PR is now conflicting (sorry for being so slow reviewing it...). It seems like it contains some useful stuff though. I'm planning to do a lot of renaming so if you want some of it merged please wait with fixing it.

**Comment by mortberg** [comment]
I'm closing this now as it has some conflicts and some of the main results are already in the library.

**Pull request closed without merging**
