### PR TITLE
use retracts to prove n-types

### PR DESCRIPTION
**Pull request by ecavallo**

### CODE REVIEW

**Comment by mortberg** [comment]
Thanks! As discussed some of the results can probably be proved even more directly in the relevant special cases

**Comment by 3abc** [comment]
> Thanks! As discussed some of the results can probably be proved even more directly in the relevant special cases

I've found a direct proof. I have it ready in Agda and I will translate to cubicaltt.

**Comment by mortberg** [comment]
@3abc I think @ecavallo  also had some more direct proofs. Please make some PRs! :-)

**Comment by mortberg** [comment]
I never spent much time optimizing the later maps in the definition as I was stuck in the middle, but it would be interesting to make progress of this now. 

@3abc Did anything come out of your experiments of defining the eliminator for truncations? (https://github.com/agda/cubical/pull/74)

FYI: I'm going to be very busy with other things for almost a month now so I don't really have time to work much on this right now, but if you experiment more please keep me posted on your findings.

**Comment by 3abc** [comment]
> @3abc Did anything come out of your experiments of defining the eliminator for truncations? ([agda/cubical#74](https://github.com/agda/cubical/pull/74))

Oh what I said above was meant to say I have direct proofs of the eliminators. I thought this PR is about the eliminators?

**Comment by mortberg** [comment]
> > @3abc Did anything come out of your experiments of defining the eliminator for truncations? ([agda/cubical#74](https://github.com/agda/cubical/pull/74))
> 
> Oh what I said above was meant to say I have direct proofs of the eliminators. I thought this PR is about the eliminators?

Not exactly. Evan just simplified the proof that various types have specific hlevels, in particular there is now no need for the standard formulation of the univalence axiom.

**Comment by 3abc** [comment]
> Not exactly. Evan just simplified the proof that various types have specific hlevels, in particular there is now no need for the standard formulation of the univalence axiom.

Oh so it's about things like `isGroupoid SET` `isTwoGroupoid GROUPOID`. I see, great.

**Pull request merged**
